JS Task-1
SaXaPhonist/JS-tasks pull request #1
Opened 2021-09-16 12:55 UTC by SaXaPhonist

2021-09-16 13:47 UTC, k-krasilnikova requested changes
Good job, but required some updates

2021-09-16 13:47 UTC, k-krasilnikova commented on task-1/task-1.js
> +const notes = require('./mock-data');
This variable looks like collection. In case we declare variables without any calculations and getters/setters - declare it with an uppercase. Otherwise - camelCase.
`const NOTES = `

2021-09-16 13:47 UTC, k-krasilnikova commented on task-1/task-1.js
> +  let arrObj = Object(this);
Why `let` declaration here? Where you will change the value of this object?

2021-09-16 13:47 UTC, k-krasilnikova commented on task-1/task-1.js
> +  let arrObj = Object(this);
Why `let` declaration here? Where you will change the value of this object?

2021-09-16 13:47 UTC, k-krasilnikova commented on task-1/task-1.js
> +const mapRes = notes.myMap((el) => ({ id: el.id, title: el.title }));
Let's try to avoid such variable names like "el", "element", "e"
Rename it please with something more acceptable for current context: (Ex: `NOTES.myMap((note) => ({ id: note.id, title: note.title}))`)

2021-09-16 13:47 UTC, k-krasilnikova commented on task-1/task-1.js
> +const testArray = [1, 1, 1, 2, 2, 3, 4, 4, 5, 5, 5, 5];
Let's declare this test array with uppercase, because it does not contain any calculations and get/set actions
`const TEST_ARRAY = `

2021-09-16 13:47 UTC, k-krasilnikova commented on task-1/task-1.js
> +  if (!arr.length || !Array.isArray(arr)) throw new Error();
Try to declare `if` statement with full structure. It will keep your code readable for other engineers.
```
if (!arr.length || !Array.isArray(arr)) {
 throw new Error();
}
```

2021-09-16 14:31 UTC, SaXaPhonist commented on task-1/task-1.js
> +  let arrObj = Object(this);
seems i missed it

2021-09-17 08:01 UTC, k-krasilnikova approved these changes

2021-09-17 16:01 UTC, merged