react 4 task
SaXaPhonist/JS-tasks pull request #15
Opened 2021-11-14 22:21 UTC by SaXaPhonist

# Task-4
## Overview
- implement full process of Authorization
 - create forms with validation (use Formik)
 - Use React-query for  api requests
- create mock server
- use redurect if user do not login yet

## [Deploy](https://saxaphonist.github.io/JS-tasks/)

2021-11-16 09:02 UTC, k-krasilnikova requested changes
Amazing!
But some changes required!

2021-11-16 09:02 UTC, k-krasilnikova commented on react-notes/src/components/overlayingAlert/overlayingAlert.jsx
> +  const [open, setOpen] = useState(false);
What is open? 
Use please `isOpen` instead. The same for the future.
```suggestion
  const [isOpen, setIsOpen] = useState(false);
```

2021-11-16 09:02 UTC, k-krasilnikova commented on react-notes/src/components/overlayingAlert/overlayingAlert.jsx
> +      <Alert severity={status} onClose={() => setOpen(false)}>
```suggestion
      <Alert severity={status} onClose={setOpen}>
```
And use please prev state inside the `setOpen` function

2021-11-17 07:50 UTC, SaXaPhonist commented on react-notes/src/components/Forms/loginForm/loginContainer.jsx
> +import { closePopup } from '../../../utils/utils';
have an error when trying to implement absolute paths ( module not found )
 i created a jsconfig.json with such script: 
 ```
{
    "compilerOptions": {
      "baseUrl": "src"
    },
    "include": ["src"]
  }
 ```
but it didn't help me, still the same error

2021-11-17 10:30 UTC, k-krasilnikova approved these changes
Fix please one more comment and it will be available to merge

2021-11-17 10:30 UTC, k-krasilnikova commented on react-notes/src/components/Forms/loginForm/loginContainer.jsx
> +  );
Use query should be defined inside api files,not container!

2021-11-17 11:24 UTC, merged